# templates/backup-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "postgresql-ha.fullname" . }}-backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pg-dump
              image: amazon/aws-cli
              command:
                - /bin/sh
                - -c
                - |
                  export PGPASSWORD=$PGPASSWORD
                  export BACKUP_FILE=/tmp/db-$(date +"%Y-%m-%d_%H-%M-%S").sql
                  pg_dump -h {{ include "postgresql-ha.fullname" . }} \
                          -U $POSTGRES_USER \
                          $POSTGRES_DB > $BACKUP_FILE
                  {{- if .Values.backup.s3.enabled }}
                  aws s3 cp $BACKUP_FILE s3://{{ .Values.backup.s3.bucket }}/$(basename $BACKUP_FILE) \
                      --region {{ .Values.backup.s3.region }} \
                      --sse AES256
                  aws s3api put-object-tagging \
                      --bucket {{ .Values.backup.s3.bucket }} \
                      --key $(basename $BACKUP_FILE) \
                      --tagging 'TagSet=[{Key=ttl,Value={{ .Values.backup.s3.ttl | default "30d" }} }]'
                  {{- else }}
                  BACKUP_DIR={{ .Values.backup.localBackupDir | default "/var/lib/postgresql/backups/$(date +\"%Y-%m-%d\")" }}
                  mkdir -p $BACKUP_DIR && \
                  mv $BACKUP_FILE $BACKUP_DIR/
                  find /var/lib/postgresql/backups/ -type d -mtime +{{ .Values.backup.localRetentionDays | default 7 }} -exec rm -rf {} +
                  {{- end }}
              env:
                - name: POSTGRES_USER
                  value: {{ .Values.postgresql.username }}
                - name: POSTGRES_DB
                  value: {{ .Values.postgresql.database }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgresql-ha.fullname" . }}
                      key: postgres-password
                {{- if .Values.backup.s3.enabled }}
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgresql-ha.fullname" . }}
                      key: aws-access-key-id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgresql-ha.fullname" . }}
                      key: aws-secret-access-key
               {{- end }}
          restartPolicy: OnFailure
          {{- if not .Values.backup.s3.enabled }}
          volumes:
            - name: backup
              emptyDir: {}
          {{- end }}
