# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-ha.fullname" . }}-config
  labels:
    app: {{- if .Values.replication.enabled }}
      {{ include "replication.name" . }}
    {{- else }}
      { include "primary.name" . }}
    {{- end }}

data:
  POSTGRES_DB: {{ .Values.postgresql.database }}
  POSTGRES_USER: {{ .Values.postgresql.username }}
  postgresql.conf: |
    {{- if .Values.replication.enabled }}
    {{ .Values.primary.postgresqlConfig }}
      hot_standby = on
      primaryConninfo: "host={{ .Values.replication.primaryHost }} port={{ .Values.service.port }} user={{ .Values.replication.replicationUser }} password={{ .Values.replication.replicationPassword }} sslmode=require"
    {{- else }}
    {{ .Values.primary.postgresqlConfig }}
    {{- end }}
  pg_hba.conf: |
    {{- if .Values.replication.enabled }}
    {{ .Values.primary.pgHbaConfiguration }}
    host    replication    {{ .Values.replication.replicationUser }}    {{ .Values.replication.primaryCIDR }}    scram-sha-256
    {{- else }}
    {{ .Values.primary.pgHbaConfiguration }}
    {{- end }}
