# templates/pgpool-deployment.yaml
 {{- if .Values.pgpool.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-ha.fullname" . }}-pgpool
  labels:
    app: pgpool
spec:
  replicas: {{ .Values.pgpool.replicaCount }}
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
        - name: pgpool
          image: {{ .Values.pgpool.image }}
          ports:
            - containerPort: {{ .Values.container.port | default 5432 }}
          env:
            - name: PGPOOL_ADMIN_USERNAME
              value: {{ .Values.pgpool.config.admin_user }}
            - name: PGPOOL_ADMIN_PASSWORD
              value: {{ .Values.pgpool.config.admin_password }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port | default 5432 }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port | default 5432 }}
            initialDelaySeconds: 30
            periodSeconds: 10
  {{- end }}
