# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-ha.fullname" . }}
  labels:
    app: { { - if .Values.replication.enabled } }
      { { include "replication.name" . } }
      { { - else } }
      { include "primary.name" . } }
      { { - end } }
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc }}
