apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-ha.fullname" . }}-backup-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.backup.s3.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.s3.secretAccessKey }}
