apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-ha.fullname" . }}-initdb
  labels:
    app: {{ include "postgresql-ha.name" . }}
data:
  {{- range $key, $val := .Values.postgresql.initdbScripts }}
    {{ $key }}: |
  {{ $val | indent 4 }}
  {{- end }}