# values.yaml
replicaCount: 2

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgresql:
  username: postgres
  password: postgres123  # will be stored in Secret
  database: mydb

container:
  name: postgres
  port: ""

replication:
  enabled: false # Default  replication false.
  replicationUser: "replica_user"  # User for replication
  replicationPassword: "your_password"
  primaryHost: <postgresql-primary>
  primaryCIDR: <Primary Host Network  CIDRs >

primary:
  name: primary
  postgresqlConfig: |-
    ssl = 'on'
    ssl_cert_file = '/tls/tls.crt'
    ssl_key_file = '/tls/tls.key'
    ssl_ca_file = '/tls/ca.crt'
    ssl_prefer_server_ciphers = on
    password_encryption = scram-sha-256
    include_if_exists = '/var/lib/postgresql/data/reload.conf'
  pgHbaConfiguration: |-
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    hostssl all             all             0.0.0.0/0               scram-sha-256
    hostssl all             all             ::/0                    scram-sha-256

replica:
  name: replica

initdbScripts:
  init-user.sh: |
    #!/bin/bash
    psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOF
    CREATE USER readonly WITH PASSWORD 'readonlypass';
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO readonly;
    EOF

backup:
  enabled: true
  localBackupDir: "/var/lib/postgresql/backups/$(date +\"%Y-%m-%d\")"
  schedule: "0 * * * *"
  s3:
    enabled: true
    ttl: 30d
    bucket: pg-s3-bucket
    region: us-east-1
    accessKeyId: "REPLACE_ME"
    secretAccessKey: "REPLACE_ME"

service:
  name: postgres
  type: ClusterIP
  port: ""
  targetPort: ""
  readOnly:
    enabled: true

resources: {}

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

pgpool:
  enabled: true
  name: pgpool
  image: bitnami/pgpool:4.3.3
  port: 5432
  replicaCount: 1
  config:
    admin_user: admin
    admin_password: admin123

tls:
  enabled: true
  secretName: postgresql-tls
  certKey: tls.key
  certCrt: tls.crt
  caCrt: ca.crt

