apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "etcd.fullname" . }}
spec:
  serviceName: {{ include "etcd.fullname" . }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "etcd.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "etcd.name" . }}
    spec:
      containers:
        - name: etcd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 2379
            - containerPort: 2380
          command:
            - /usr/local/bin/etcd
            - --name=$(POD_NAME)
            - --data-dir=/etcd-data
            - --initial-advertise-peer-urls=http://$(POD_IP):2380
            - --listen-peer-urls=http://0.0.0.0:2380
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://$(POD_IP):2379
            - --initial-cluster-token=etcd-cluster-1
            - --initial-cluster={{ include "etcd.initialCluster" . }}
            - --initial-cluster-state=new
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
